### ISSUE TITLE
Unable to use input() in python - vscode.dev

### ISSUE THREAD

**Issue by salmin89** [formulahendry/vscode-code-runner-for-web#2]
Hi,
I'm not sure if this is possible or I'm missing something. Can I use x = input('..') while on the web version? vscode.dev

Doing so right now gives me this error:
```
PythonError: Traceback (most recent call last):
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 494, in eval_code_async
    await CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 345, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
EOFError: EOF when reading a line
```

**Comment by formulahendry** [comment]
Reading user input is not supported for now.
